### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by BrotherJing** [dyweb/gitlab-android#12]
- [ ] Open file, commit, issue(可以参考 labcoat
- [ ] Parse content in rss item and open in app(rss feed中只有URL和description，解析成相应的动作在app内打开 自己实现
- [ ] Process link in textview(一些textview中有URL，有的还是相对路径，直接浏览器无法打开，需要自己解析
- [ ] Optimize notification(后台service poll rss，实际上并没有定时poll。。

暂时想到这么多，可以补充
